### ISSUE TITLE
Django 1.9: ImportError: cannot import name 'import_by_path'

### ISSUE THREAD

**Issue by FabriceSalvaire** [appliedsec/djangular#40]
traceback:

  File "/opt/python-virtual-env/py35/lib/python3.5/site-packages/djangular/templatetags/djangular_tags.py", line 9, in <module>
    from djangular.core.urlresolvers import get_all_remote_methods, get_current_remote_methods, get_urls
  File "/opt/python-virtual-env/py35/lib/python3.5/site-packages/djangular/core/urlresolvers.py", line 7, in <module>
    from django.utils.module_loading import import_by_path
ImportError: cannot import name 'import_by_path'

**Comment by cmck** [comment]
django.utils.module_loading.import_by_path was deprecated since Django 1.7. 
djangular.core.urlresolvers should use django.utils.module_loading.import_string instead, which behaves the same way.

It appears that the project works with Django 1.9 after this change so I will provide a pull request

**Comment by Dean-Christian-Armada** [comment]
I also had this issue, fix please

**Comment by nicholasserra** [comment]
Hello, this issue is not related to this repository, but is instead an issue with django-angular (which also used to be named angular).

https://github.com/jrief/django-angular

This can be closed.
